image: node:16-alpine

cache:
  key: $CI_JOB_NAME
  paths:
    - .npm/

before_script:
  - apk add --no-cache jq docker
  - npm ci --cache .npm --prefer-offline

build:
  script:
    - npm run build
    - sh build.sh
