image: node:16-alpine

stages:
  - build
  - deploy

cache:
  key: $CI_JOB_NAME
  paths:
    - .npm/

before_script:
  - apk add --no-cache jq docker docker-compose

build:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "dist/iot-dash"
    policy: push
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build

deploy:
  only:
    - tags
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "dist/iot-dash"
    policy: pull
  needs:
    - build
  stage: deploy
  script:
    - sh build.sh
    - sh deploy.sh